<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    style="display: block; animation-play-state: running"
    class="animate-spin"
  >
    <circle
      cx="50"
      cy="50"
      fill="none"
      stroke="#464646"
      stroke-width="10"
      r="35"
      stroke-dasharray="164.93361431346415 56.97787143782138"
      transform="matrix(1,0,0,1,0,0)"
      style="animation-play-state: paused"
    ></circle>
    <!-- generated by https://loading.io/ -->
  </svg>
</template>
